### ISSUE TITLE
Patrón de diseño Factory

### ISSUE THREAD

**Issue by BrendaArellano** [tectijuana/pypdd6a-Archived#2]
Fecha de Exposición Lunes 18 de abril
Arellano Garcia Brenda Gabriela @BrendaArellano 
Macedo Vidrio Evelyn Macedo @EvelynMacedo 
Nuñez Canizalez Miguel Alejandro @miguelnc93

**Comment by IoTeacher** [comment]
@BrendaArellano @miguelnc93 @EvelynMacedo tiene 100 en Python y estan liberados de la material de PDD, muchas gracias son excelentes estudiantes y deseandoles el éxito en su vida academica y profesional.

René
